Coal:
  upgrade: 100
  spawn: 100
Copper:
  upgrade: 100
  spawn: 100
Lapis:
  upgrade: 100
  spawn: 100
Iron:
  upgrade: 100
  spawn: 100
Gold:
  upgrade: 100
  spawn: 100
Redstone:
  upgrade: 100
  spawn: 100
Diamond:
  upgrade: 100
  spawn: 100
Emerald:
  upgrade: 100
  spawn: 100
Quartz:
  spawn: 100
Ancient_debris:
  spawn: 100
Glowstone:
  spawn: 100
Blackstone:
  spawn: 100
Soulsand:
  spawn: 100
Soulsoil:
  spawn: 100
Nether_gold:
  spawn: 100
Magma_block:
  spawn: 100
Netherrack:
  spawn: 100